"""empty message

Revision ID: 089acbd2ba12
Revises: 1ce9e79f317b
Create Date: 2025-06-12 16:25:18.348125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '089acbd2ba12'
down_revision: Union[str, None] = '1ce9e79f317b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lnk_chat_moderator_table',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('moderator_id', sa.BigInteger(), nullable=False),
    sa.Column('ba_perm', sa.Boolean(), nullable=False),
    sa.Column('ban_perm', sa.Boolean(), nullable=False),
    sa.Column('kick_perm', sa.Boolean(), nullable=False),
    sa.Column('mute_perm', sa.Boolean(), nullable=False),
    sa.Column('warn_perm', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['moderator_id'], ['moderator_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('moderator_table', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('moderator_table', 'mute_perm')
    op.drop_column('moderator_table', 'ban_perm')
    op.drop_column('moderator_table', 'warn_perm')
    op.drop_column('moderator_table', 'user_id')
    op.drop_column('moderator_table', 'chat_id')
    op.drop_column('moderator_table', 'updated_at')
    op.drop_column('moderator_table', 'ba_perm')
    op.drop_column('moderator_table', 'kick_perm')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moderator_table', sa.Column('kick_perm', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('moderator_table', sa.Column('ba_perm', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('moderator_table', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False))
    op.add_column('moderator_table', sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('moderator_table', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('moderator_table', sa.Column('warn_perm', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('moderator_table', sa.Column('ban_perm', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('moderator_table', sa.Column('mute_perm', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('moderator_table', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_table('lnk_chat_moderator_table')
    # ### end Alembic commands ###
