"""право на линковку nullable

Revision ID: 0eedb9e67357
Revises: ffc6a5da5cee
Create Date: 2025-07-03 14:15:27.087212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eedb9e67357'
down_revision: Union[str, None] = 'ffc6a5da5cee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moderator_chat_table', sa.Column('linkto_perm', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moderator_chat_table', 'linkto_perm')
    # ### end Alembic commands ###
