"""empty message

Revision ID: 12ea95efb28a
Revises: 089acbd2ba12
Create Date: 2025-06-14 00:22:38.615259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12ea95efb28a'
down_revision: Union[str, None] = '089acbd2ba12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'lnk_chat_moderator_table', 'chat_table', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lnk_chat_moderator_table', type_='foreignkey')
    # ### end Alembic commands ###
