"""empty message

Revision ID: 1359db6c438d
Revises: d168bddbd7d1
Create Date: 2025-06-30 17:05:40.503142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1359db6c438d'
down_revision: Union[str, None] = 'd168bddbd7d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('distribution_table', 'last_msg_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('distribution_table', 'last_msg_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
