"""изменение периода с int на timedelta

Revision ID: 162d9a628f6b
Revises: 5543c92a190c
Create Date: 2025-06-21 17:23:52.967998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '162d9a628f6b'
down_revision: Union[str, None] = '5543c92a190c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mute_rest_table', 'period',
               existing_type=sa.BIGINT(),
               type_=sa.Interval(),
               existing_nullable=False,
               postgresql_using="period * interval '1 second'"
               )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mute_rest_table', 'period',
               existing_type=sa.Interval(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               postgresql_using="EXTRACT(EPOCH FROM period)::bigint"
               )
    # ### end Alembic commands ###
