"""удален chat_id из ba_orm

Revision ID: 2c920fba4710
Revises: 9e56c2e45659
Create Date: 2025-07-15 15:31:09.629473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c920fba4710'
down_revision: Union[str, None] = '9e56c2e45659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ba_rest_table', 'chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ba_rest_table', sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
