"""empty message

Revision ID: 44577107e9d5
Revises: 602d90deefe7
Create Date: 2025-06-11 19:47:01.716733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44577107e9d5'
down_revision: Union[str, None] = '602d90deefe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moderator_table', sa.Column('ba_perm', sa.Boolean(), nullable=False))
    op.add_column('moderator_table', sa.Column('ban_perm', sa.Boolean(), nullable=False))
    op.add_column('moderator_table', sa.Column('kick_perm', sa.Boolean(), nullable=False))
    op.add_column('moderator_table', sa.Column('mute_perm', sa.Boolean(), nullable=False))
    op.add_column('moderator_table', sa.Column('warn_perm', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moderator_table', 'warn_perm')
    op.drop_column('moderator_table', 'mute_perm')
    op.drop_column('moderator_table', 'kick_perm')
    op.drop_column('moderator_table', 'ban_perm')
    op.drop_column('moderator_table', 'ba_perm')
    # ### end Alembic commands ###
