"""empty message

Revision ID: 472e94e27d12
Revises: e800d51b631b
Create Date: 2025-06-30 14:40:53.845164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '472e94e27d12'
down_revision: Union[str, None] = 'e800d51b631b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distribution_table', sa.Column('next_dist_date', sa.DateTime(), nullable=False))
    op.alter_column('distribution_table', 'interval',
               existing_type=sa.INTEGER(),
               type_=sa.Interval(),
               existing_nullable=False,
               postgresql_using="interval * interval '1 second'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('distribution_table', 'interval',
               existing_type=sa.Interval(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               postgresql_using="EXTRACT(EPOCH FROM interval)::bigint")
    op.drop_column('distribution_table', 'next_dist_date')
    # ### end Alembic commands ###
