"""добавление айди сообщения

Revision ID: 6f8662816350
Revises: 472e94e27d12
Create Date: 2025-06-30 14:47:05.473390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f8662816350'
down_revision: Union[str, None] = '472e94e27d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distribution_table', sa.Column('msg_id', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('distribution_table', 'msg_id')
    # ### end Alembic commands ###
