"""empty message

Revision ID: 78891bee98f0
Revises: 52687212dfb4
Create Date: 2025-06-04 23:09:38.873592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78891bee98f0'
down_revision: Union[str, None] = '52687212dfb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_restriction_table',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('by_moderator_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('action_type', postgresql.ENUM('WARN', 'MUTE', 'BAN', 'TOTAL_BAN', name='action_type'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('moderator_table', sa.Column('chat_id', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moderator_table', 'chat_id')
    op.drop_table('user_restriction_table')
    # ### end Alembic commands ###