"""сохранение айди собщения ба

Revision ID: 798718586388
Revises: 2c920fba4710
Create Date: 2025-07-16 15:10:05.077517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '798718586388'
down_revision: Union[str, None] = '2c920fba4710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ba_rest_table', sa.Column('msg_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ba_rest_table', 'msg_id')
    # ### end Alembic commands ###
