"""local perm

Revision ID: 8a5c4ec7002a
Revises: 8bdbe9951c5d
Create Date: 2025-07-18 16:56:28.744239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a5c4ec7002a'
down_revision: Union[str, None] = '8bdbe9951c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moderator_chat_table', 'local_perm',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moderator_chat_table', 'local_perm',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
