"""local perm nullable

Revision ID: 8bdbe9951c5d
Revises: 798718586388
Create Date: 2025-07-18 16:55:59.668744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bdbe9951c5d'
down_revision: Union[str, None] = '798718586388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moderator_chat_table', sa.Column('local_perm', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moderator_chat_table', 'local_perm')
    # ### end Alembic commands ###
