"""empty message

Revision ID: 9554747ce911
Revises: 12ea95efb28a
Create Date: 2025-06-15 17:59:27.729874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9554747ce911'
down_revision: Union[str, None] = '12ea95efb28a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderator_chat_table',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('moderator_id', sa.BigInteger(), nullable=False),
    sa.Column('ba_perm', sa.Boolean(), nullable=False),
    sa.Column('ban_perm', sa.Boolean(), nullable=False),
    sa.Column('kick_perm', sa.Boolean(), nullable=False),
    sa.Column('mute_perm', sa.Boolean(), nullable=False),
    sa.Column('warn_perm', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat_table.id'], ),
    sa.ForeignKeyConstraint(['moderator_id'], ['moderator_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('lnk_chat_moderator_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lnk_chat_moderator_table',
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('moderator_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ba_perm', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('ban_perm', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('kick_perm', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('mute_perm', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('warn_perm', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat_table.id'], name=op.f('lnk_chat_moderator_table_chat_id_fkey')),
    sa.ForeignKeyConstraint(['moderator_id'], ['moderator_table.id'], name=op.f('lnk_chat_moderator_table_moderator_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lnk_chat_moderator_table_pkey'))
    )
    op.drop_table('moderator_chat_table')
    # ### end Alembic commands ###
