"""период мута None при муте навсегда

Revision ID: 9e56c2e45659
Revises: c8359ea41b4d
Create Date: 2025-07-15 12:42:32.363250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e56c2e45659'
down_revision: Union[str, None] = 'c8359ea41b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moderator_chat_table', 'perm_perm',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('mute_rest_table', 'period',
               existing_type=postgresql.INTERVAL(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mute_rest_table', 'period',
               existing_type=postgresql.INTERVAL(),
               nullable=False)
    op.alter_column('moderator_chat_table', 'perm_perm',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
