"""изменение прав пользователей с nullable

Revision ID: c8359ea41b4d
Revises: ac64e6700be6
Create Date: 2025-07-10 00:52:48.767419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8359ea41b4d'
down_revision: Union[str, None] = 'ac64e6700be6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_perm_table',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('can_send_messages', sa.Boolean(), nullable=False),
    sa.Column('can_send_audios', sa.Boolean(), nullable=False),
    sa.Column('can_send_documents', sa.Boolean(), nullable=False),
    sa.Column('can_send_photos', sa.Boolean(), nullable=False),
    sa.Column('can_send_videos', sa.Boolean(), nullable=False),
    sa.Column('can_send_video_notes', sa.Boolean(), nullable=False),
    sa.Column('can_send_voice_notes', sa.Boolean(), nullable=False),
    sa.Column('can_send_polls', sa.Boolean(), nullable=False),
    sa.Column('can_send_other_messages', sa.Boolean(), nullable=False),
    sa.Column('can_add_web_page_previews', sa.Boolean(), nullable=False),
    sa.Column('can_change_info', sa.Boolean(), nullable=False),
    sa.Column('can_invite_users', sa.Boolean(), nullable=False),
    sa.Column('can_pin_messages', sa.Boolean(), nullable=False),
    sa.Column('can_manage_topics', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_perm_table',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('can_send_messages', sa.Boolean(), nullable=False),
    sa.Column('can_send_audios', sa.Boolean(), nullable=False),
    sa.Column('can_send_documents', sa.Boolean(), nullable=False),
    sa.Column('can_send_photos', sa.Boolean(), nullable=False),
    sa.Column('can_send_videos', sa.Boolean(), nullable=False),
    sa.Column('can_send_video_notes', sa.Boolean(), nullable=False),
    sa.Column('can_send_voice_notes', sa.Boolean(), nullable=False),
    sa.Column('can_send_polls', sa.Boolean(), nullable=False),
    sa.Column('can_send_other_messages', sa.Boolean(), nullable=False),
    sa.Column('can_add_web_page_previews', sa.Boolean(), nullable=False),
    sa.Column('can_change_info', sa.Boolean(), nullable=False),
    sa.Column('can_invite_users', sa.Boolean(), nullable=False),
    sa.Column('can_pin_messages', sa.Boolean(), nullable=False),
    sa.Column('can_manage_topics', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('moderator_chat_table', sa.Column('perm_perm', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moderator_chat_table', 'perm_perm')
    op.drop_table('user_perm_table')
    op.drop_table('chat_perm_table')
    # ### end Alembic commands ###
