"""активность рассылки и айди последней

Revision ID: d168bddbd7d1
Revises: fa5a0b9eb0a2
Create Date: 2025-06-30 17:03:40.983480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd168bddbd7d1'
down_revision: Union[str, None] = 'fa5a0b9eb0a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distribution_table', sa.Column('last_msg_id', sa.BigInteger(), nullable=False))
    op.add_column('distribution_table', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('distribution_table', 'is_active')
    op.drop_column('distribution_table', 'last_msg_id')
    # ### end Alembic commands ###
