"""право на линковку

Revision ID: d5dcc84e597a
Revises: 0eedb9e67357
Create Date: 2025-07-03 14:20:36.132438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5dcc84e597a'
down_revision: Union[str, None] = '0eedb9e67357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moderator_chat_table', 'linkto_perm',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moderator_chat_table', 'linkto_perm',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
