"""право на закрытие чата у админов удаление nullable

Revision ID: e800d51b631b
Revises: f477d52358ee
Create Date: 2025-06-22 22:52:35.195163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e800d51b631b'
down_revision: Union[str, None] = 'f477d52358ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moderator_chat_table', 'close_perm',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moderator_chat_table', 'close_perm',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
