"""изменение названия тыблицы чатов рассылки

Revision ID: ee975e5ebce8
Revises: 1359db6c438d
Create Date: 2025-07-01 15:46:28.151452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee975e5ebce8'
down_revision: Union[str, None] = '1359db6c438d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distribution_chat_table',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('distribution_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat_table.id'], ),
    sa.ForeignKeyConstraint(['distribution_id'], ['distribution_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('distibution_chat_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distibution_chat_table',
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('distribution_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat_table.id'], name=op.f('distibution_chat_table_chat_id_fkey')),
    sa.ForeignKeyConstraint(['distribution_id'], ['distribution_table.id'], name=op.f('distibution_chat_table_distribution_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('distibution_chat_table_pkey'))
    )
    op.drop_table('distribution_chat_table')
    # ### end Alembic commands ###
