"""право на закрытие чата у админов с nullable

Revision ID: f477d52358ee
Revises: 162d9a628f6b
Create Date: 2025-06-22 22:51:37.156721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f477d52358ee'
down_revision: Union[str, None] = '162d9a628f6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moderator_chat_table', sa.Column('close_perm', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moderator_chat_table', 'close_perm')
    # ### end Alembic commands ###
