"""связь рассылки и чата

Revision ID: fa5a0b9eb0a2
Revises: 6f8662816350
Create Date: 2025-06-30 16:41:15.429909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa5a0b9eb0a2'
down_revision: Union[str, None] = '6f8662816350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distibution_chat_table',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('distribution_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat_table.id'], ),
    sa.ForeignKeyConstraint(['distribution_id'], ['distribution_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('distribution_table', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('distribution_table', 'chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distribution_table', sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('distribution_table', 'name')
    op.drop_table('distibution_chat_table')
    # ### end Alembic commands ###
