"""empty message

Revision ID: ffc6a5da5cee
Revises: ee975e5ebce8
Create Date: 2025-07-02 14:02:56.636015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffc6a5da5cee'
down_revision: Union[str, None] = 'ee975e5ebce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distribution_chat_table', sa.Column('last_msg_id', sa.BigInteger(), nullable=True))
    op.drop_column('distribution_table', 'last_msg_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distribution_table', sa.Column('last_msg_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('distribution_chat_table', 'last_msg_id')
    # ### end Alembic commands ###
